# Generated by Django 4.1 on 2022-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=100)),
                ('empCategory', models.CharField(blank=True, max_length=100)),
                ('empCity', models.CharField(max_length=50)),
                ('empOrg', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
